### ISSUE TITLE
Set up single breakpoint in Sass

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#1]

**Comment by sashaburchuk** [comment]
I set the breakpoint at min-width: 768px for now. However the navigation changes at 510px on needmoredesigns.com. 

I was thinking that was two narrow for two columns so I used 768px. 

Separate breakpoint for the nav, or is the 768px one okay for now?

**Comment by brigleb** [comment]
:+1:

**Comment by sashaburchuk** [comment]
We can always change this if we need to but I'm going to close this because 768px is working well for us.
