### ISSUE TITLE
Add swipeable slideshow to site to display portfolio pieces

### ISSUE THREAD

**Issue by sashaburchuk** [needmore/needmore-11-years#13]
I personally really like Slides JS because it's never broken on me and isn't too much of a performance hit but I'm open to suggestions!

http://www.slidesjs.com/

**Comment by sashaburchuk** [comment]
Going to try using slick instead: http://kenwheeler.github.io/slick/

**Comment by brigleb** [comment]
@sashaburchuk My advice here is to just make a branch for each attempt, even from the branch for this feature, so you can throw that one away when it doesn't work for you, instead of having to undo all your work. Use the Git!

**Comment by sashaburchuk** [comment]
Aside from maybe fine-tuning when we design-review this page, this is done. Although we do also need to resize all of the images that we're using for these slideshows so that they are 640px by 480px. Should we close this issue?

**Comment by sashaburchuk** [comment]
![screen shot 2015-05-13 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/4923907/7621729/d6bd2f84-f97d-11e4-817a-e1084a1d3fc1.png)
![screen shot 2015-05-13 at 2 49 15 pm](https://cloud.githubusercontent.com/assets/4923907/7621739/ead29e78-f97d-11e4-81a7-7ba471183b5e.png)

**Comment by brigleb** [comment]
Yeah we may as well leave this open until we fix he left/right arrow graphics and maybe also resize the graphics. Also this vector is wrong...
