### ISSUE TITLE
background-image opacity

### ISSUE THREAD

**Issue by zebron** [needmore/needmore-11-years#19]
Sasha and I couldn't figure out how to give the background-image an opacity with out affecting everything that was wrapped up in the `.has-backgrouind` `div`.	

Location of said file:  `src/scss/_year-background-images.scss`

Here is an example of where the `div` lives in our `index.html`

    <div class="has-background"> 
	    <h2 class="sticky-year fixedsticky">2004</h2> 
	    <article class="note"> 
			<p>Needmore incorporated on April 1, 2004. We were based out of a bedroom in the Hawthrone neighborhood of Southeast Portland</p> 
		</article> 
	</div>

 - We tried this
   https://css-tricks.com/snippets/css/transparent-background-images/

For now we are just going with slightly opaque images to let the background color for each section bleed through until we can find a CSS solution.

**Comment by brigleb** [comment]
Let's review this together!

**Comment by sashaburchuk** [comment]
We may have fixed this using background sizing? 100% width, 50% height (more or less depending on how much content there is overlaying that section).

**Comment by brigleb** [comment]
So I think per our discussion and what I put the following pull request we have a pretty good idea, I just have to see it in practice. Let me know when we can maybe peek at that!

https://github.com/needmore/needmore-11-years/pull/29

**Comment by sashaburchuk** [comment]
Oh doy. Now I understand. I read your other comment first and was confused. Sure we'll get these up there right away.

**Comment by sashaburchuk** [comment]
All of the background images have been added. Closing : )
