### ISSUE TITLE
add class to float content responsively

### ISSUE THREAD

**Issue by sashaburchuk** [needmore/needmore-11-years#20]
.left will float content 50px to the left of the midline
.right will float content 50px to the right of the midline
.center will center content with a top/bottom margin of $padding

at breakpoint and below floats will be removed, all content will be centered

**Comment by sashaburchuk** [comment]
OK - all done with this. Just floated left and right based on the edge of the opposite margin, using 55%. 
https://github.com/needmore/needmore-11-years/tree/features/20-floats

**Comment by brigleb** [comment]
:+1:
