### ISSUE TITLE
List features needed by JS and candidate plugins

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#3]
Off the top of my head we would need

* Slider or similar for background images triggered
* Lazy load
* Twitter embeds (done?)
* Modernizr *only if needed*

I feel like we talked about a few others.

**Comment by sashaburchuk** [comment]
Twitter embeds are done and they are responsive!
I'll work on lazy load

**Comment by brigleb** [comment]
No no. Don't work on Lazy Load. We need to chat first and look over our timeline.

**Comment by brigleb** [comment]
@sashaburchuk I updated the description of this issue, we can mark it done but return if we find particularly good JS resources to add.

**Comment by brigleb** [comment]
Candidates:

* http://mikefowler.me/crossfade.js/
* http://bttrlazyloading.julienrenaux.fr/demo/animations.php
