### ISSUE TITLE
All the things we need to finish : )

### ISSUE THREAD

**Issue by sashaburchuk** [needmore/needmore-11-years#37]
- Content for year sections: notes, albums, portfolio-work, photos, slideshows, tweets, instagrams - currently it's all placeholder content
- The correct vectors (device img/screen/ and prev next arrows) for slideshows and also the slides that will go in to them
- Guidelines for how to style different media types (instagram, tweet, etc) if we need to style them differently from how they look now

...I'll keep adding to this list in comments. Doest that work?

**Comment by zebron** [comment]
works for me
