### ISSUE TITLE
Style year sections

### ISSUE THREAD

**Issue by sashaburchuk** [needmore/needmore-11-years#5]

**Comment by zebron** [comment]
Alrighty, did some h2 styling for the year section dividers as well as some styling to the h1 with help from Sasha and the gang. Just waiting to see if it's ready to be merged into the master branch. https://github.com/needmore/needmore-11-years/tree/features/5-style-year-sections

**Comment by zebron** [comment]
![screen shot 2015-05-06 at 2 26 55 pm](https://cloud.githubusercontent.com/assets/8154039/7504052/fd99240a-f3fb-11e4-8f3d-76625e6ded0e.png)

**Comment by sashaburchuk** [comment]
Go for it. LMK if you run in to anything tricky.

**Comment by zebron** [comment]
Ran into some tricky stuff. Worked it out with Gregor. Thanks dude.

**Comment by brigleb** [comment]
Just FYI these are going to look rather different now. They are going to be in circles, centered on desktop and possibly mobile. That can be done with CSS so we can chat.

**Comment by sashaburchuk** [comment]
I just peeked at Gritchelle's designs. Putting things in circles is chill. Might need a little guidance when it comes to using scroll events but maybe I can just figure it out on my own? :fingers-crossed
