### ISSUE TITLE
Attempt Instagram embed

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#8]
In theory, we can do this much the same way we're doing with Twitter.

https://help.instagram.com/513918941996087

Can we please try one and see how well it works?

**Comment by sashaburchuk** [comment]
Yeah that works really well - but we might want to use it sparingly. Look at how much code is part of the embed: 

<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="4" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/2RY7jhKF_n/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_top">Design is in the details.</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">A photo posted by Needmore Designs (@needmoredesigns) on <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-05-04T19:27:14+00:00">May 4, 2015 at 12:27pm PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>

**Comment by brigleb** [comment]
Post that as a snippet

```
separate with ``` on blank lines
```

**Comment by sashaburchuk** [comment]
We could probably optimize that embed a little by linking to the js only once and then removing the inline styles and replacing them with styles in a file?

**Comment by brigleb** [comment]
@sashaburchuk can you link to the branch this was addressed with?

**Comment by sashaburchuk** [comment]
Hey @brigleb - it's been merged back in to master now but we didn't make a branch for it specifically. It's a little hard to spot but it is wrapped in a blockquote inside of an article with a class of instagram. https://github.com/needmore/needmore-11-years/blob/master/index.html
