### ISSUE TITLE
Add sticky nav, exactly like our main website

### ISSUE THREAD

**Issue by brigleb** [needmore/needmore-11-years#9]
The navigation from needmoredesigns.com should be basically replicated on this site.

**Comment by sashaburchuk** [comment]
This is done on mobile. Do it for all viewport widths while I'm at it, or?

**Comment by brigleb** [comment]
@sashaburchuk yes, please do. Post screen shots when you complete something like this so I can easily see that there aren't obvious issues. Thanks!

**Comment by sashaburchuk** [comment]
OK, I've taken care of this. Except this is the feature that I worked on while on master and not on features/header. I've merged the changes back in to master - do you want me to merge them in to features/header as well? 
![screen shot 2015-05-06 at 11 49 48 am](https://cloud.githubusercontent.com/assets/4923907/7502909/466f6caa-f3f4-11e4-943e-c71535430b1d.png)
![screen shot 2015-05-06 at 11 50 03 am](https://cloud.githubusercontent.com/assets/4923907/7502911/4b2ff96c-f3f4-11e4-92f6-5d71f7c99cef.png)
